/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacegrafica;

import javax.swing.JOptionPane;
import java.util.Iterator;
import classededados.Aluno;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import persistencia.*;

/**
 *
 * @author Giu
 */
public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    private void imprimirNaGrid(ArrayList<Aluno> dados){
        try{
            DefaultTableModel model =  (DefaultTableModel) jTableGridAlunos.getModel();
            model.setNumRows(0);
            int pos = 0;
            while(pos < dados.size()){
                String[] linha = new String[4];
                Aluno obj = dados.get(pos);
                linha[0]= obj.getNome();
                //linha[0]= obj.getSobre_Nome().split(0, 1);
                linha[1]= obj.getCurso();
                linha[2]= obj.getSituacao();
                linha[3]= obj.getEnfase();
                model.addRow(linha);
                pos++;
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGridAlunos = new javax.swing.JTable();
        jToggleButton_Nome = new javax.swing.JToggleButton();
        jButton_SobreNome = new javax.swing.JButton();
        jButton_EnfaseNome = new javax.swing.JButton();
        jButton_CursoNome = new javax.swing.JButton();
        jButton_SN = new javax.swing.JButton();
        jButton_SCN = new javax.swing.JButton();
        jButton_ECN = new javax.swing.JButton();
        jButton_CEN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableGridAlunos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableGridAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Curso", "Situação", "Enfase"
            }
        ));
        jScrollPane1.setViewportView(jTableGridAlunos);

        jToggleButton_Nome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButton_Nome.setText("Ordenar Pelo Nome");
        jToggleButton_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_NomeActionPerformed(evt);
            }
        });

        jButton_SobreNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_SobreNome.setText("Ordenar Pelo Sobre Nome");
        jButton_SobreNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SobreNomeActionPerformed(evt);
            }
        });

        jButton_EnfaseNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_EnfaseNome.setText("Enfase e Nome");
        jButton_EnfaseNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EnfaseNomeActionPerformed(evt);
            }
        });

        jButton_CursoNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_CursoNome.setText("Curso e Nome");
        jButton_CursoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CursoNomeActionPerformed(evt);
            }
        });

        jButton_SN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_SN.setText("Situação e Nome");
        jButton_SN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SNActionPerformed(evt);
            }
        });

        jButton_SCN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_SCN.setText("Situação, Curso e Nome");
        jButton_SCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SCNActionPerformed(evt);
            }
        });

        jButton_ECN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_ECN.setText("Enfase, Curso e Nome");
        jButton_ECN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ECNActionPerformed(evt);
            }
        });

        jButton_CEN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_CEN.setText("Curso, Enfase e Nome");
        jButton_CEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CENActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_SCN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButton_Nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_ECN, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_SobreNome))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_CEN)
                            .addComponent(jButton_EnfaseNome, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_SN, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_CursoNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 979, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton_Nome)
                    .addComponent(jButton_SobreNome)
                    .addComponent(jButton_EnfaseNome)
                    .addComponent(jButton_CursoNome))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_SCN)
                    .addComponent(jButton_ECN)
                    .addComponent(jButton_CEN)
                    .addComponent(jButton_SN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_NomeActionPerformed
        // TODO add your handling code here:
        try{
            String nome = "./src/dados/RelatorioDasEnfases.csv";
            OrdenadoPorNome objeto = new OrdenadoPorNome(nome);
            imprimirNaGrid(objeto.listagemDeAlunosNome());
        }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_jToggleButton_NomeActionPerformed

    private void jButton_EnfaseNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EnfaseNomeActionPerformed
        // TODO add your handling code here:
        try{
            String nome = "./src/dados/RelatorioDasEnfases.csv";
            OrdenadoPorEnfaseNome objeto = new OrdenadoPorEnfaseNome(nome, nome);
            imprimirNaGrid(objeto.listagemDeAlunosEnfaseNome());
        }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_jButton_EnfaseNomeActionPerformed

    private void jButton_CursoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CursoNomeActionPerformed
        // TODO add your handling code here:
        try{
            String nome = "./src/dados/RelatorioDasEnfases.csv";
            OrdenarPorCursoNome objeto = new OrdenarPorCursoNome(nome, nome);
            imprimirNaGrid(objeto.listagemDeAlunosCursoNome());
        }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_jButton_CursoNomeActionPerformed

    private void jButton_SCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SCNActionPerformed
        // TODO add your handling code here:
        try{
            String nome = "./src/dados/RelatorioDasEnfases.csv";
            OrdenarPorSituacaoCursoNome objeto = new OrdenarPorSituacaoCursoNome(nome, nome, nome);
            imprimirNaGrid(objeto.listagemDeAlunosSituacaoCursoNome());
        }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_jButton_SCNActionPerformed

    private void jButton_ECNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ECNActionPerformed
        // TODO add your handling code here:
        try{
            String nome = "./src/dados/RelatorioDasEnfases.csv";
            OrdenarPorEnfaseCursoNome objeto = new OrdenarPorEnfaseCursoNome(nome, nome, nome);
            imprimirNaGrid(objeto.listagemDeAlunosEnfaseCursoNome());
        }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_jButton_ECNActionPerformed

    private void jButton_CENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CENActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        try{
            String nome = "./src/dados/RelatorioDasEnfases.csv";
            OrdenarPorCursoEnfaseNome objeto = new OrdenarPorCursoEnfaseNome(nome, nome, nome);
            imprimirNaGrid(objeto.listagemDeAlunosCursoEnfaseNome());
        }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_jButton_CENActionPerformed

    private void jButton_SNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SNActionPerformed
        // TODO add your handling code here:
        try{
            String nome = "./src/dados/RelatorioDasEnfases.csv";
            OrdenarPorSituacaoNome objeto = new OrdenarPorSituacaoNome(nome, nome);
            imprimirNaGrid(objeto.listagemDeAlunosSituacaoNome());
        }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_jButton_SNActionPerformed

    private void jButton_SobreNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SobreNomeActionPerformed
        // TODO add your handling code here:
        try{
            String nome = "./src/dados/RelatorioDasEnfases.csv";
            OrdenarPorSobreNome objeto = new OrdenarPorSobreNome(nome);
            imprimirNaGrid(objeto.listagemDeAlunosSobreNome());
        }catch(Exception erro){
            JOptionPane.showMessageDialog(rootPane, erro);
        }
    }//GEN-LAST:event_jButton_SobreNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_CEN;
    private javax.swing.JButton jButton_CursoNome;
    private javax.swing.JButton jButton_ECN;
    private javax.swing.JButton jButton_EnfaseNome;
    private javax.swing.JButton jButton_SCN;
    private javax.swing.JButton jButton_SN;
    private javax.swing.JButton jButton_SobreNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableGridAlunos;
    private javax.swing.JToggleButton jToggleButton_Nome;
    // End of variables declaration//GEN-END:variables
}
